#!/bin/bash
printf '%o⧵n' $(( 5#$( echo $WATER | tr water 01234) + 5#$( echo $STIR | trr stir. 01234 ) )) | tr 01234567 shtbeolhcecho $(printf %o $(($((5#$(echo $WATER | tr 'water' '01234'))) + $((5#$(echo $STIR | tr 'stir.' '01234'))))) | tr '01234567' 'bestschol') 
